version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/welcome/front"
    schedule:
      interval: "daily"
      timezone: "Asia/Tokyo"
  - package-ecosystem: "npm"
    directory: "/section-template/section-01/front"
    schedule:
      interval: "daily"
      timezone: "Asia/Tokyo"
  - package-ecosystem: "npm"
    directory: "/exercises/section-01/front"
    schedule:
      interval: "daily"
      timezone: "Asia/Tokyo"
