version: '3'
services:
  db:
    image: mysql:8.0.28
    environment:
      MYSQL_ROOT_PASSWORD: p@ssw0rd!
    networks:
      - section-06-app-network
    # volumes: 
      # - ./db:/var/lib/mysql
    command: ["--default-authentication-plugin=mysql_native_password"]
    ports: 
      - 3306:3306
  app:
    build: ./section-06-app
    container_name: section-06-app
    command: "rails s -b 0.0.0.0 -p 3000"
    volumes:
      - ./section-06-app:/app
    ports:
      - 31000:3000
    networks:
      - section-06-app-network
    depends_on:
      - db
  front:
    build: ./section-06-app-front
    container_name: section-06-app-front
    volumes:
      - ./section-06-app-front:/front
      - section-06-app-front__node_modules:/front/node_modules
    ports:
      - 32000:3000
    networks:
      - section-06-app-network
volumes:
  section-06-app-front__node_modules:
networks:
  section-06-app-network:
    external: true
